version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:v1.7.3
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - mcp_network

  embedding:
    build:
      context: .
      dockerfile: embedding.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - qdrant
    networks:
      - mcp_network

volumes:
  qdrant_data:
    driver: local

networks:
  mcp_network:
    driver: bridge 